### ISSUE TITLE
Server Endpoint: User level statistics should return stats for each day in datastore for particular user

### ISSUE THREAD

**Issue by BobEvans** [google/paco#1216]

**Comment by ianspiro** [comment]
The current format for stats looks like this:

count: 1
participants: Array[1]
  0: Object
    $$hashKey: "object:56"
    todaySelfReportCount: 1
    todaySignalCount: 0
    todaySignalResponseCount: 0
    totalSelfReportCount: 11
    totalSignalCount: 0
    totalSignalResponseCount: 0
    who: "test@example.com"

We may need to generalize a bit to support the multi-day stats. Is there a use-case for multi-day stats for multiple users or is it sufficient to provide multi-day for just a single user? If the latter, then what about:

count: 3
who:  "test@example.com"
days: Array[1]
  0: Object
    date: 11/20/2015
    selfReportCount: 1
    signalCount: 2
    signalResponseCount: 1
  1: Object
    date: 11/21/2015
    selfReportCount: 0
    signalCount: 2
    signalResponseCount: 2
  2: Object
    date: 11/22/2015
    selfReportCount: 0
    signalCount: 2
    signalResponseCount: 1
totals: Object
    selfReportCount: 1
    signalCount: 6
    signalResponseCount: 4

Maybe we could get away from the notion of 'today' and instead use explicit dates. In the original case of getting today / total stats for each user, this is tricky since the simplest thing would be to use the latest date of any data that appears. This would be incorrect if you have one user in a later timezone who causes 'today' to exclude the data we actually care about.
