### ISSUE TITLE
Web UI: Contextual Help: 

### ISSUE THREAD

**Issue by BobEvans** [google/paco#1301]
Groups tab: (hover) Define surveys, data collection and tasks in your experiment
Duration: (hover, contextual link, or underline text?) When this experiment will start and end
Triggers: (hover, contextual link, or underline text?) Probably contextual help that provides more room to explain. Briefly, the text: Define a moment when your experiment will run and what it will do when it runs. 

Additionally, Optionally: (These aren't great).
Add Scheduled Trigger: Enter a schedule for your experiment and the actions to take at the scheduled times.
Add Event Trigger: Define the sensor events that will cause your experiment to run and the actions to take at those events.

Under Scheduled Trigger:
General help text, probably contextual text that explains how schedules and actions work. For example:
Define one or more schedules at which action(s) will be performed. When any of the schedules transpires the action(s) will be performed in the order they are defined. The schedules should not overlap.

Edit Schedule Popup
Daily Schedule Selected:
User Editable (Hover): Controls whether users can customize the schedule for themselves.
Editable On Join (Hover): When checked, this restricts schedule editing to only when they join the experiment.
Label (underline text): A name for this time that will be shown to the user.

Random Sampling (ESM):
Minimum between: Change underline text to "minimum number of minutes between signals."
Start Time and End Time: underline or hover, "The start and end of the daily window in which the user will be signaled"
Include Weekends: (hover) When checked, the weekend days will be signaled

Edit Action:
Create Notification to Participate selection: Brief text under the Pull down list:
"Signal the user to respond with a System Notification. Links to the Input Form."
Under Timeout (underline text): "minutes until notification is withdrawn and marked as a missed signal"
Under Snooze Repeats (underline text): Add 1 re-signaling of the System Notification.
Under Snooze time (underline text): minutes to wait before re-signaling.

Create Notification Message: (Note this still needs to provide a message text field). Brief text under the Pull down list: 
"Send the user a message as a System Notification."
Under Timeout (underline text): "minutes until notification is withdrawn and marked as a missed signal"
Under Snooze Repeats (underline text): Add 1 re-signaling of the System Notification.
Under Snooze time (underline text): minutes to wait before re-signaling.

Execute script:
"Write custom javascript functions to execute when triggered. See Wiki page for Javascript api."

Under Event Trigger:
Change Buffer to Minimum Buffer
Edit CUE: When Pull down choice is App Started, App Stopped:
"Enter the full name of the Android app package and activity to use as the trigger"
Edit CUE: When Pull down choice is Paco Action:
"Enter the unique string that this trigger will recognize to be sent by other Android apps"

Inputs: Define the questions that your experiment will ask, if any.
Under Input X:
Conditional (hover): Only show this question when the conditional expression is true. 
The Condition text field should have hint text or underline text and contextual help 
Hint or underline text should be an example, input_variable_name == 2
Contextual help should describe a couple of examples and point to the wiki page (yet to be created, but, the user-friendly version of this page: https://github.com/google/paco/wiki/Input-Conditional-Expression-Parser).

Advanced Section:
End of Day Group: Reference another Group in order to follow up on the daily responses from that group. 
Background Listening: Listen for data sent from other apps and record it in the experiment data set.
When selected, a sourceIdentifier text box appears: (underline text)
"Enter the unique string to be sent by other Android apps"

Log app usage and browser history: Record apps used and sites visited in the experiment data set.
Override form display: Build your own web survey form in HTML, Javascript and CSS.
Feedback: Change the message shown to users after responding to a survey form.
Feedback underline text for different types:
Static Message: This message will be shown to users after they save a survey response.
Retrospective: The user will be shown basic charts and visualization of their responses.
Responsive: Not yet implemented. Do not use.
Custom Code:  Build your own feedback message in HTML, Javascript and CSS.
Disable Feedback: The user will be shown no message. Use this when overriding form display and showing feedback as part of that.

Admin Tab:
Administrators underline text: Add the word Google in front of email addresses to clarify that these are google accounts.

Published Audience underline text: Add the word Google in front of email addresses to clarify that these are google accounts.

Extra Types of Data Collection (to be renamed to "Data Collection Permissions to Request")
Provide a one line text below the title, or, use contextual help to explain that the user will be asked to grant permission to collect these types of data during informed consent. Also, explain that the custom code that accesses these data will verify that these permissions were requested and throw AccessDenied exceptions if not.

Extra Types of Data Collection, individual permissions: Add the same hovers on these as on the Advanced tab of Groups

Phone Details should be "Extra Data to Collect".

Informed Consent underline text: "Declare to the user what data you will collect, how it will be used and who will have access to it."

Data Action (on already-saved experiment):
Hover text: View & Export Collected Data

Stats Action(on already-saved experiment):
Hover text: View Participation Statistics

Stats View
Really this page could use a contextual help explanation of how it works.
Response column label hover: "Count of user responses to signaled events (received)"
Signal column label hover: "Count of System notifications sent to user (received)"
Self report label hover: "Count of un-signaled user responses"

Note, the split between today and Total might mean we modify the help text to add "Today" or "Total" respectively.

**Comment by NickAraujo** [comment]
Other help text presentation ideas:
* Overlay tutorial
* Dismissible help box (tied to a variable stored in the user's account)
* "Learn more" that links to a specific online help page

Additional comments inline:

Groups tab: (hover) Define surveys, data collection and tasks in your experiment
Duration: (hover, contextual link, or underline text?) When this experiment will start and end
Triggers: (hover, contextual link, or underline text?) Probably contextual help that provides more room to explain. Briefly, the text: Define a moment when your experiment will run and what it will do when it runs.

Additionally, Optionally: (These aren't great).
Add Scheduled Trigger: Enter a schedule for your experiment and the actions to take at the scheduled times.
Add Event Trigger: Define the sensor events that will cause your experiment to run and the actions to take at those events.

Under Scheduled Trigger:
General help text, probably contextual text that explains how schedules and actions work. For example:
Define one or more schedules at which action(s) will be performed. When any of the schedules transpires the action(s) will be performed in the order they are defined. The schedules should not overlap.
> Consider re-arranging and labeling the schedules and actions to better reflect how schedules ("At any of these times:") and actions ("Do these actions in order:") work.

Edit Schedule Popup
Daily Schedule Selected:
User Editable (Hover): Controls whether users can customize the schedule for themselves.
Editable On Join (Hover): When checked, this restricts schedule editing to only when they join the experiment.
Label (underline text): A name for this time that will be shown to the user.
> Maybe present this as 3 mutually-exclusive choices (e.g., via dropdown): "Allow user to edit schedule: At any time, Only when joining, Never"

Random Sampling (ESM):
> Consider "Frequency: ____ times per [day]"

Minimum between: Change underline text to "minimum number of minutes between signals."

> "Minimum delay between signals: ____ minutes"

Start Time and End Time: underline or hover, "The start and end of the daily window in which the user will be signaled"

> Additionally help probably not needed

Include Weekends: (hover) When checked, the weekend days will be signaled

> Additionally help probably not needed. Consider just presenting checkboxes for each day.


Edit Action:
Create Notification to Participate selection: Brief text under the Pull down list:
"Signal the user to respond with a System Notification. Links to the Input Form."

> Consider showing the notification message (perhaps in lieu of help text), and potentially allowing users to customize it.

Under Timeout (underline text): "minutes until notification is withdrawn and marked as a missed signal"
Under Snooze Repeats (underline text): Add 1 re-signaling of the System Notification.
Under Snooze time (underline text): minutes to wait before re-signaling.

Create Notification Message: (Note this still needs to provide a message text field). Brief text under the Pull down list: 
"Send the user a message as a System Notification."
Under Timeout (underline text): "minutes until notification is withdrawn and marked as a missed signal"
Under Snooze Repeats (underline text): Add 1 re-signaling of the System Notification.
Under Snooze time (underline text): minutes to wait before re-signaling.

Execute script:
"Write custom javascript functions to execute when triggered. See Wiki page for Javascript api."

Under Event Trigger:
Change Buffer to Minimum Buffer
> Consider just removing "Buffer" and just leaving "Minimum delay between signals ____ minutes"

Edit CUE: When Pull down choice is App Started, App Stopped:
"Enter the full name of the Android app package and activity to use as the trigger"
Edit CUE: When Pull down choice is Paco Action:
"Enter the unique string that this trigger will recognize to be sent by other Android apps"

Inputs: Define the questions that your experiment will ask, if any.
Under Input X:
Conditional (hover): Only show this question when the conditional expression is true. 
The Condition text field should have hint text or underline text and contextual help 
Hint or underline text should be an example, input_variable_name == 2
Contextual help should describe a couple of examples and point to the wiki page (yet to be created, but, the user-friendly version of this page: https://github.com/google/paco/wiki/Input-Conditional-Expression-Parser).

> Can we get rid of the index and present this in a more intuitive way?, e.g., "Ask if: [question (dropdown)] [boolean (dropdown)] [user identifiable choices specific to that question (dropdown)]" Can also retain a "custom" option for those who want advanced features.

Advanced Section:
End of Day Group: Reference another Group in order to follow up on the daily responses from that group.

> Should this only be an option if multiple groups exist? 

Background Listening: Listen for data sent from other apps and record it in the experiment data set.
When selected, a sourceIdentifier text box appears: (underline text)
"Enter the unique string to be sent by other Android apps"

Log app usage and browser history: Record apps used and sites visited in the experiment data set.

> There was a question about whether this logging occurred continuously throughout the experiment, or only at scheduled/triggered times. Maybe revise to include this: "Continuously record apps used and sites visited." May also just edit the title in lieu of help text.

Override form display: Build your own web survey form in HTML, Javascript and CSS.
> "Customize your form" How will they know what the form is?--the term is not used previously. Also, should provide a link to formatting help docs when checked and/or default HTML.

Feedback: Change the message shown to users after responding to a survey form.
> "Show after completing the input form:" Maybe this should be included in the input section?--should this option even be possible if they don't create an input form?

Feedback underline text for different types:
Static Message: This message will be shown to users after they save a survey response.
> Consider instead of current label: "Text" or "message" - Probably does not need additional help.

Retrospective: The user will be shown basic charts and visualization of their responses.
> Consider instead of current label: "Summary of their responses" - Probably does not need additional help.

Responsive: Not yet implemented. Do not use.
> Should remove from the list until implemented.

Custom Code: Build your own feedback message in HTML, Javascript and CSS.
Disable Feedback: The user will be shown no message. Use this when overriding form display and showing feedback as part of that.

Admin Tab:
Administrators underline text: Add the word Google in front of email addresses to clarify that these are google accounts.

Published Audience underline text: Add the word Google in front of email addresses to clarify that these are google accounts.

Extra Types of Data Collection (to be renamed to "Data Collection Permissions to Request")
> Seems like this should be under the "Advanced" groups tab, with a note that they require additional permissions, e.g.,: "Location information (requires user consent)." Maybe if checked, they get added to the default informed consent.

Provide a one line text below the title, or, use contextual help to explain that the user will be asked to grant permission to collect these types of data during informed consent. Also, explain that the custom code that accesses these data will verify that these permissions were requested and throw AccessDenied exceptions if not.
> Maybe the note about custom code checking lives wherever the custom code lives - seems like this detail would not be relevant for all users.

Extra Types of Data Collection, individual permissions: Add the same hovers on these as on the Advanced tab of Groups

Phone Details should be "Extra Data to Collect".

Informed Consent underline text: "Declare to the user what data you will collect, how it will be used and who will have access to it."
> Maybe populate with a default informed consent that must be changed to publish. Feel like this should be under Basics tab.

Data Action (on already-saved experiment):
Hover text: View & Export Collected Data

Stats Action(on already-saved experiment):
Hover text: View Participation Statistics

Stats View
Really this page could use a contextual help explanation of how it works.
Response column label hover: "Count of user responses to signaled events (received)"
Signal column label hover: "Count of System notifications sent to user (received)"
Self report label hover: "Count of un-signaled user responses"

Note, the split between today and Total might mean we modify the help text to add "Today" or "Total" respectively.

**Comment by NickAraujo** [comment]
Here are my suggestions for contextual help links to the help doc:

* (Already implemented) Whenever the triggers frame expands - Help: Triggers & Actions, https://docs.google.com/document/d/1f_kkTtvb4TKWIoseYfbOuX6D-8TOiZ3pIkjJ_sI6eGM/edit#heading=h.ax1l2jwvrkxo
* Whenever the input frame expands - Help: Inputs, https://docs.google.com/document/d/1f_kkTtvb4TKWIoseYfbOuX6D-8TOiZ3pIkjJ_sI6eGM/edit#heading=h.rfj5zaiuklqq
* (Already implemented) Whenever a user selects conditional input - Help: Conditional Inputs, https://docs.google.com/document/d/1f_kkTtvb4TKWIoseYfbOuX6D-8TOiZ3pIkjJ_sI6eGM/edit#heading=h.p8esi25lpyip
* (Already implemented) Whenever the advanced frame expands - Help: Advanced Data Collection, https://docs.google.com/document/d/1f_kkTtvb4TKWIoseYfbOuX6D-8TOiZ3pIkjJ_sI6eGM/edit#heading=h.le5i22y0oxrv
* Whenever a user adds an experiment group (on the 2nd group) - Help: Experiment Groups, https://docs.google.com/document/d/1f_kkTtvb4TKWIoseYfbOuX6D-8TOiZ3pIkjJ_sI6eGM/edit#heading=h.3xccjkfufpig
* When user selects cue on App Started or App Stopped, in popup, next to the source field - Help: App Triggers, https://docs.google.com/document/d/1f_kkTtvb4TKWIoseYfbOuX6D-8TOiZ3pIkjJ_sI6eGM/edit#heading=h.roauu5tvawhu

**Comment by ianspiro** [comment]
I'm closing this issue, though the general effort of contextual help is ongoing.

**Comment by BobEvans** [comment]
Good idea. There are, I think, a couple of other bugs around this, well, at least one. So, this is worth closing.
