### ISSUE TITLE
Web UI: User should be able to delete individual actions, cues, or schedules.

### ISSUE THREAD

**Issue by NickAraujo** [google/paco#1302]
To delete individual actions, cues, or schedules, the user must leave the items "undefined" or delete the entire Schedule/Event Trigger Group.

![image](https://cloud.githubusercontent.com/assets/15365617/10893100/d7b27442-815b-11e5-98e8-88ee3b0690c8.png)

**Comment by NickAraujo** [comment]
Also consider a way to re-order individual schedules, cues, and actions from the "Groups" screen (see above) as well as from the Schedule pop-up:

![image](https://cloud.githubusercontent.com/assets/15365617/11099622/46431446-8861-11e5-98b0-6f01d35ca610.png)

**Comment by ianspiro** [comment]
The first part, the ability to delete schedules and triggers, was resolved in https://github.com/google/paco/commit/c59b7dbeb77df8102f89e5c6f13bde25d1c1f421

If you play around on pacostage.appspot.com, you can see it. I don't think this particular merge to develop has been deployed as a release to pacoapp yet.

As for reordering, schedules have an inherent order since they are in time. Likewise, I don't think order matters for cues but it may matter for actions.

**Comment by NickAraujo** [comment]
While not actually meaningful to the way Paco works, the order of a cue or a list of times may have meaning for the user--e.g., I'd go mad if I couldn't switch 12:00pm and 9:00am in the screenshot above, and editing the times is an inconvenient fix. I'd say re-ordering is a nice-to-have, but if we build a solution for actions then we should just apply that solution to all lists.

**Comment by NickAraujo** [comment]
I should add inputs to the list of items that should have delete and re-order ability.

**Comment by BobEvans** [comment]
It looks like all of these issues are fixed. If not, please file each individual piece as a new ticket.
