### ISSUE TITLE
Accessing completed experiment responses after fix #1688

### ISSUE THREAD

**Issue by acknitter** [google/paco#1690]
My research team and I were previously collecting data through paco experiments. A participant submitted responses through the paco app in the last month, just after fix #1688 and when the website went offline. Is there any way to recover this data? 

Any suggestions would be appreciated.

**Comment by BobEvans** [comment]
Hi,

If they were submitting data after the server went down, there is no way to recover it from the server side  because it is on the phone (no server to upload to). 

I have turned the server back on for one day to help. 

If you can have them submit another response on the phone, then it should try to upload everything as well as the new response. Then you can download that data. 

Please let me know if this will work soon. I will have to turn the server back off so as not to incur more charges. 

Thanks,
Bob

**Comment by acknitter** [comment]
Hi Bob,

Apologies I didn't see your reply sooner!

We greatly appreciate the offer. We don't think it's feasible on our end to have the participant submit another response, so we'll leave it be.

Thanks very much for your help.
